### ISSUE TITLE
Error while loading shared libraries: libicuuc.so.74 [Arch Linux]

### ISSUE THREAD

**Issue by khan5ula** [meganz/MEGAsync#950] opened 2024-05-21 10:22 UTC
Megasync seems to depend on an older package of icu. The newest version currently available on Arch Linux is 75.1-1.

Launching megasync results in: `megasync: error while loading shared libraries: libicuuc.so.74: cannot open shared object file: No such file or directory`

**Comment by simonwiles** [comment] 2024-05-21 17:00
This just happened to me a couple of minutes ago too. libicu has been upgraded from 74 to 75, that's all. The AUR has an icu74 package that should solve the problem, but that's not building properly right now (someone needs to update the hash), so I just did a clean build of the megasync package and everything's fine (if you're using megasync-bin obviously you'll need to switch to megasync).

**Comment by simonwiles** [comment] 2024-05-21 17:00
Duplicate of #951.

**Comment by khan5ula** [comment] 2024-05-22 17:54
> This just happened to me a couple of minutes ago too. libicu has been upgraded from 74 to 75, that's all. The AUR has an icu74 package that should solve the problem, but that's not building properly right now (someone needs to update the hash), so I just did a clean build of the megasync package and everything's fine (if you're using megasync-bin obviously you'll need to switch to megasync).

Thanks for your input. Downloading icu74 from AUR seemed to do it for now.

**Comment by regisz** [comment] 2024-05-30 06:37
> > This just happened to me a couple of minutes ago too. libicu has been upgraded from 74 to 75, that's all. The AUR has an icu74 package that should solve the problem, but that's not building properly right now (someone needs to update the hash), so I just did a clean build of the megasync package and everything's fine (if you're using megasync-bin obviously you'll need to switch to megasync).
> 
> Thanks for your input. Downloading icu74 from AUR seemed to do it for now.

Ahh, you saved my life :-).
Thx a lot, this solve my problem too.

**Comment by tekunikaru** [comment] 2024-06-03 05:08
This seems to be similar issues in the past. Is there a way to solve this in a more general matter?

**Comment by vtmateos** [comment] 2024-06-07 07:15
Dear users,
A new update for ARCH has been pushed in order to fix these issues. Please update and let us know if there is any other problem. Thanks.

**Closed by vtmateos** 2024-06-07 07:15 UTC

**Comment by nkia-christoph** [comment] 2024-06-25 09:10
as a hotfix, just install the ice74 aur package
