### ISSUE TITLE
MEGAsync icon in XFCE4 sistem tray 

### ISSUE THREAD

**Issue by WyRe** [meganz/MEGAsync#25] opened 2016-07-26 16:45 UTC
Hi all! I am still with xfce4 MEGA integration and ... I would like ask about this glitch:

http://i.imgur.com/lJiF8F6.png

Do you think this could be your issue? or Maybe is XFCE devs thing? 

Thank you so much! :P

**Comment by polmr** [comment] 2016-08-22 17:35
@WyRe Sorry for the late response. I am unable to reproduce in an XFCE environment. It scales properly. However, xfce allows you to define the maximum icon size for the notification area: 
Panel -> panel preferences -> Items -> Notification Area -> Edit current selected item (cogwheel)

**Comment by WyRe** [comment] 2016-08-22 19:42
Well, I've got this issue because I've setup my maximum size of the icons in the system tray in 15px (the lowest) And the issue appears in system startup when xfwm4 is loaded from system init (for first time). 

When I modify this value (maximum size of the icons in the system tray) with right click over system tray > properties, the issue is fixed and icon returns to normal.

**Comment by polmr** [comment] 2016-08-23 08:26
Interesting .... I've been able to reproduce this with other distributions. It is definitely some XFCE thing. It only happens when you use **the lowest size** (being that 15, 13, 12 or whatever <I'm guessing that depends on resolution/other appearance settings>). This is solved by increasing the size, or reloading the pannel with: `xfce4-panel -r`. I would suggest you to write to XFCE guys. IMHO this is a corner case situation, so as to implement any dirty fix from our side (forcing a panel reload everytime megasync opens/using a tiny icon/...)

**Comment by WyRe** [comment] 2016-08-23 09:05
Ok, I'll try to contact with them and keep informing here, thank you so much!

**Comment by polmr** [comment] 2016-11-15 11:37
It's been quite a long while... but, @WyRe is there any news on that?

**Comment by WyRe** [comment] 2016-11-15 13:31
Well, I've posted the issue in the bug tracker, but I haven't got answers, 

https://bugzilla.xfce.org/show_bug.cgi?id=11323

**Comment by Pival81** [comment] 2016-11-15 18:57
@WyRe you should create a new issue, not post on one dated 2014.

**Comment by WyRe** [comment] 2016-11-23 08:23
It seems have been solved for `xfce4-panel 4.12.1-1` in ArchLinux. I don't know if it has to do with my post, I don't think so but I've tested several times (rebooting) and now the icon is resized properly.

**Comment by polmr** [comment] 2016-11-28 09:58
@WyRe, I am afraid that I cannot reproduce it. Anyway, I understand that this is a bug for xfce. megasync does nothing actively with the panel.

**Comment by Pival81** [comment] 2016-11-28 10:02
I've read somewhere else that you just need to use the appindicator, just install alltray and:
```alltray megasync```

**Comment by WyRe** [comment] 2016-11-28 10:30
@polmr really is with 'intelligent autohide', sorry.

**Comment by polmr** [comment] 2016-11-28 11:41
@WyRe, I've just been able to reproduce it. It seems xfce panel is having problems with Qt5 apps. See: https://forum.manjaro.org/t/flickering-panel-when-set-autohidden-on-click-notification-area-qt-icons/3810. It's been reported here already: https://bugzilla.xfce.org/show_bug.cgi?id=11733.

**Comment by polmr** [comment] 2017-04-26 12:05
I'm closing this one since it is not an actual megasync issue. Hopefully this ticket will serve as reference if anyone is experiencing the same problem

**Closed by polmr** 2017-04-26 12:05 UTC
