### ISSUE TITLE
List of all files at Cloud

### ISSUE THREAD

**Issue by Gabarito007** [meganz/MEGAsync#76] opened 2017-03-06 19:35 UTC
How to get a list (txt, csv or any text like format) of all my files storaged at Cloud?
Is there a simple CLI (Command Line) for Megacmd to reach that?
I've already read https://github.com/meganz/sdk/blob/master/examples/megacmd/README.md, but it seems to makes and build (compile?) the interface and/or handles SDK or something for advanced and heavy users. Is there a EXE file or another way just to get the list of files?

**Comment by polmr** [comment] 2017-03-07 15:18
You can download megacmd from https://mega.nz/cmd, and use the command "find" after loging in.

**Comment by Gabarito007** [comment] 2017-03-07 19:36
Thank you for MegaCmd.
I noted that file names aren't Unicode.
How to handle non-English file names?
And how to direct MegaCmd outputs to a text file? Pehaps pipe symbol (>) won't work.
Trying to use this
ls > list.txt
and got error "Couldn't find >
Thx

**Comment by polmr** [comment] 2017-09-07 08:07
Apologies for the (so) late response, 
We have released a new version of MEGAcmd with certain support for non-ASCII characters for Windows (available at https://mega.nz/cmd).
To redirect the outputs to a file you should use non-interactive mode (see `help --non-interactive` and https://github.com/meganz/sdk/blob/master/examples/megacmd/README.md for further info)

**Comment by Gabarito007** [comment] 2017-09-07 12:33
Thank you.
I got that version you linked.
But cannot run without error.
I was not told to run Server before run MEGAcmdShell.
I got this:
[Server not running](https://s26.postimg.org/xwaz9oddl/server.png)

After run Server, cmdShell is unable to receive commands.
Each character delays to show:
[Cannot enter 'help' command](https://s26.postimg.org/ulmm9sng9/client_and_server.png)

Finally, once shutdown cmdShell, Server starts to output rows of error:
[Bunch of errors](https://s26.postimg.org/jolal10op/server_error.png)

I hope I'm not missing something and doing wrong.
:)

Thanks.

**Comment by polmr** [comment] 2017-09-07 12:52
Ey @Gabarito007 , thanks for reporting that. 
Did you install MEGAcmd just for you or all users?

**Comment by Gabarito007** [comment] 2017-09-07 12:53
For all users.
Also, I have MegaSync installed.
It was not running when I did MegaCmd tests.

**Comment by polmr** [comment] 2017-09-07 13:15
That's odd. The thing is:
The shell tries to connect to the server. if it is not running it, it tries to open it. 
Also, for security reasons, we dont allow the server to be running by one user (say admin) and the client by another. If you close everything and kill the process MEGAcmd.exe you might be able to get things working again. Anyway, I suggest you to try to reinstall it only for the current user

**Comment by Gabarito007** [comment] 2017-09-07 13:21
More info: Output error of shell about path is C:\Users\i7\AppData\Local\MegaCmd, but such path doesn't exist.
Instead, program is at C:\ProgramData\MEGAcmd.

**Comment by Gabarito007** [comment] 2017-09-07 13:30
Uninstalled and reinstall for current user.
Shell could not start Server.
[Pipe](https://s26.postimg.org/o26t05sc9/Pipe.png)

And Server could not run:
[Fatal error](https://s26.postimg.org/86mkalr5l/Named_Pipe.png)

**Comment by polmr** [comment] 2017-09-07 14:24
What version of windows are you using?
Please, ensure you have closed all megacmd processes before reinstalling. Did you do an uninstall before reinstalling for current user?

**Comment by Gabarito007** [comment] 2017-09-07 17:49
Sorry for delay to respond.
Yes, I uninstalled before reinstall.
And yes, all Mega process was closed before doing that.
I'm at Windows Seven SP1.

**Comment by polmr** [comment] 2017-09-11 08:54
@Gabarito007 I managed to reproduce some of your issues when installing as admin. But everything works fine after killing all MEGAcmd tasks and starting over. Does the issue still occur after restarting your computer?

**Comment by Gabarito007** [comment] 2017-09-11 10:41
Last tryout, few minutes ago, I reinstalled MEGAcmd (just for me) and noticed that it goes to C:\Users\i7\AppData\Local\MEGAcmd. Installation program didn't ask for folder to install.
Once finished, I kept "Run MEGAcmd" checkbox and it showed this screen:
[Failed to access server](https://s26.postimg.org/rv8iiejy1/mega-cmd-client.png)
(i7 is my username)

Weird that instalation won't allow to choose a folder to install.
And MEGAcmdShell cannot seeing that default folder.

I started server manually and it show some error like "Fatal error with communications" quickly and closed:
[Communications](https://s26.postimg.org/sbtq4u7p5/installing-communications.jpg).

Do you want to do a TeamViewer session with my computer to see for yourself and look for solutions?
Make an appointment and I'll see my schedule.

**Comment by polmr** [comment] 2017-09-11 12:36
We don't have avilability to use TeamViewer right now, but let´s start over. Please, close all megacmd instances. and then uninstall megacmd, by executing:
`C:\ProgramData\MEGAcmd\uninst.exe
`
and
`C:\Users\i7\AppData\Local\MEGAcmd\uninst.exe
`
Now reinstall MEGAcmd. Please, do not execute the installer as admin! Also, just being paranoid: DO NOT CHECK the execute checkbox after installing.

Once you have it installed anew. Please, ensure there is no megacmd.exe process running:
Task manager should not show a MEGAcmd.exe process and if you execute this in powershell:
`tasklist.exe | select-string megacmd
`
the output should be empty.
Again being paranoid: execute this in powershell to kill all MEGAcmd.exe intances:
`wmic process where "description like '%%MEGAcmd.exe'" DELETE
`
Now let´s execute MEGAcmd the less automated way possible: 
A) MEGAcmd server:
1) execute powershell
2) type "whoami" (this should output XXXX/i7)
3) execute megacmd server in powershell:
`C:\Users\i7\AppData\Local\MEGAcmd\MEGAcmd.exe
`
B) MEGAcmd Shell:
1) execute powershell in a new window
2) type "whoami" (this should output XXXX/i7)
3) execute megacmd server in powershell:
`C:\Users\i7\AppData\Local\MEGAcmd\MEGAcmdShell.exe`

Hope this will fix your issue. However we should try to fix the checking when executing both the server and the shell as admin.

**Comment by Gabarito007** [comment] 2017-09-11 13:07
>	Please, close all megacmd instances. and then uninstall megacmd, by executing:
>	C:\ProgramData\MEGAcmd\uninst.exe
>	and
>	C:\Users\i7\AppData\Local\MEGAcmd\uninst.exe

Here, we have a problem: there is no folder MEGAcmd at C:\ProgramData.
I uninstalled it via C:\Users\i7\AppData\Local\MEGAcmd

>	Now reinstall MEGAcmd.

Done.

>	Please, do not execute the installer as admin!

But there is only one user at my machine, and he is admin...

>	Also, just being paranoid: DO NOT CHECK the execute checkbox after installing.

Done.

>	Once you have it installed anew. Please, ensure there is no megacmd.exe process running:
>	Task manager should not show a MEGAcmd.exe process and if you execute this in powershell:
>	tasklist.exe | select-string megacmd
>	the output should be empty.

Done. Empty output.

>	Again being paranoid: execute this in powershell to kill all MEGAcmd.exe intances:
>	wmic process where "description like '%%MEGAcmd.exe'" DELETE

Done. "No instance avaiable" output.

>	Now let´s execute MEGAcmd the less automated way possible:
>	A) MEGAcmd server:
>	    execute powershell
>	    type "whoami" (this should output XXXX/i7)

Done. "i7-pc\i7" output.

>	    execute megacmd server in powershell:
>	    C:\Users\i7\AppData\Local\MEGAcmd\MEGAcmd.exe

Done. No error this time. :)
["Listening to petitions..."](https://s26.postimg.org/5jb68e1rt/powershell0.png)

>	B) MEGAcmd Shell:
>	    execute powershell in a new window
>	    type "whoami" (this should output XXXX/i7)

Done. "i7-pc\i7" output.

>	    execute megacmd server in powershell:
>	    C:\Users\i7\AppData\Local\MEGAcmd\MEGAcmdShell.exe

Done. But I got the next screens:

[PowerShell 1](https://s26.postimg.org/d5o4x9ym1/powershell1.png)
[PowerShell 2](https://s26.postimg.org/lcg4ouoop/powershell2.png)

>	Hope this will fix your issue.

Not this time, yet...

I suspect something about the wrong folder C:\ProgramData.
Such folder doesn't exist.

**Comment by Gabarito007** [comment] 2017-09-11 13:12
Also, there is only one user at machine and he is admin.

Other info: I have MEGAsync installed, but it was not running during MEGAcmd tests.
At C:\Program\Data I do have MEGAsync folder, but not MEGAcmd one.

**Comment by polmr** [comment] 2017-09-11 17:38
@Gabarito007 , here you have an installer that disables the check of the ownership of the Named Pipe used for communications between server and shell: https://mega.nz/#!Fd4ylBAB!55_DXRh4sJGDUPeJqaRHtV4z5GH_kB_BXptGQja5rx0
It should bypass your issue. Please, give it a try

**Comment by Gabarito007** [comment] 2017-09-11 17:56
> @Gabarito007 , here you have an installer that disables the check of the ownership of the Named Pipe used for communications between server and shell:

Success!
No more errors!
MEGAcmdShell could start MEGAcmd server and all runs fine.
😀 😀😀😀😀

**Comment by polmr** [comment] 2017-09-11 18:31
@Gabarito007 , since we want to keep the check available, could you please ensure that you can also use MEGAcmd with this installer:  https://mega.nz/#!sYgGEZKK!XwqfSm7VqIlmic0v483vRrS2DyxA3NEGMcuYht7DuTw ???
This one keeps the check but with some fix to deal with admin case. Thus, we will be able to incorporate the fix to our official packages and you can keep MEGAcmd updated

**Comment by Gabarito007** [comment] 2017-09-11 18:43
Uninstalled previous version and reinstalled that last one.
Output:
```
Server not running. Initiating in the background...
Unmatched owner - current user -> Administradores - i7
ERROR: Pipe owner does not match current user!
MEGA CMD>
```
All instalations is just for me (not everyone).

**Comment by polmr** [comment] 2017-09-12 08:32
@Gabarito007 , sorry to bother you again. There was an issue in the new code that made it fail in Windows 7. This should be fixed here: https://mega.nz/#!ddg02BRK!NlFotxrdymb1Uy-0_qz34rAtpvsIb_cYHRVVCMMarQ0. Would you care to try it?

**Comment by Gabarito007** [comment] 2017-09-12 08:45
Hi, polmr.
You don't bother at all. I'm happy to helping.

This latest version is running fine without error!
😀 

I have a question: how to redirect ls command to a txt file?
I tried `ls -o list.txt` and `find -o list.txt` without success.

**Comment by Gabarito007** [comment] 2017-09-12 08:49
And how to stop a long listing job?
CTRL-C closes MEGAcmd window.

**Comment by polmr** [comment] 2017-09-12 08:52
Happy to hear that! 

To output to a file, you need to use non-interactive mode. I'd recommend you to read this: https://github.com/meganz/sdk/tree/master/examples/megacmd and also read the output of `help --non-interactive`. If you have further cuestion, don't hesitate to ask.

In the interactive mode (the shell), we currently don't have support for stopping commands I'm afraid

**Comment by Gabarito007** [comment] 2017-09-12 08:59
Yessss!

I got it!
And now, I can have a list of files at MEGA cloud.
😀 😀 😀 😀 😀 😀 😀 😀 😀 😀 😀 😀 😀 

If you want more tests, feel free to call me again.
See ya.

**Comment by polmr** [comment] 2017-09-15 08:40
New package available at https://mega.nz/cmd should fix this issue

**Closed by polmr** 2017-09-15 08:40 UTC

**Comment by Gabarito007** [comment] 2017-09-15 13:00
Hi, polmr.

Sorry to come back to this issue after you close the thread, but I think you would need to know this.
After fetch the list of files at cloud, I noticed that, sometimes, few non-ASCII characters appears in a wrong way.

Example:
Cd100/Dicas/Códigos do f��rum 12 - LaTeX.txt

Note that at the same line we see two ways to display the same non-ASCII character.

The right way would be this:
Cd100/Dicas/Códigos do f**ó**rum 12 - LaTeX.txt

'ó' and '��' are the same thing, even though they are displayed differently.
**At the same line**
Hex:
C3 B3   -   EF BF BD EF BF BD
UTF-8 code.

This behavior uses to occurs at other lines, randomly, with others non-ASCII characters.

**Comment by Gabarito007** [comment] 2017-09-15 13:07
Explaining more: around 80% of the list are displayed correctly. Few times they aren't.
And at the same line we find correct and wrong display.
Something is going well, but a few needs to fix.

That is not important for me, but I think you may want to know.

**Comment by polmr** [comment] 2017-09-18 08:11
Ey @Gabarito007 , may I ask you to open a new issue here: github.com/meganz/sdk explaining this? Thus, we can more easily follow it up. In any case, I'm unable to reproduce it. It may be something related with different normalized encoding of such character `ó`. Is there anyway you can provide us one of the offending files? (maybe exporting the file **and** also sending it via email/attachment). If you don't want to share it publicly, you can send it to support@mega.nz and reference the corresponding github issue.

**Comment by Gabarito007** [comment] 2017-09-18 11:05
Hi, polmr.

New issue opened.
Done.

List of files with abnormal characters display sent to support@mega.nz.
Done.
