### ISSUE TITLE
Is this app going to be maintained?

### ISSUE THREAD

**Issue by technikker** [meganz/MEGAsync#1017] opened 2024-11-10 19:57 UTC
What is Mega's intention regarding this project?  Is there a plan, or is it time to move on?

For about a year now there have been non stop issues.  Made the mistake today of trying to update to 5.6.0, and it's now unusable.  In the interim I will attempt to downgrade to a previous version, but the stability and regressions have reached a point where this is no longer a viable product, which is very disappointing because I've used this for years, and past versions have served me well, and seemed to be faster than google drive.

Looking at other longstanding issues, it appears this repository is barely being maintained.  These new "features", while good on paper, don't work well, if at all, while existing functionality that worked for years is being broken.

I'm wondering if Mega has cut some engineering staff, because this last year has been a radical departure from a stable, working product.  You could just make this open source and let the community fix it for you, because no one's going to pay for this with all the issues that didn't used to exist.

**Comment by vtmateos** [comment] 2024-11-11 16:13
Hi,

Thank you for your valuable feedback.

While it’s true that we’re expanding our product portfolio with exciting new projects, this hasn’t impacted our commitment to improving our desktop app. In fact, we've released several updates over the past few months, and we’re currently working on two more versions scheduled for release by year-end, each with significant enhancements.

Starting from version 5.X, we introduced a new sync engine, which is more efficient and addresses many issues that the previous algorithm couldn’t handle. The old sync engine had limitations in certain cases, but the new engine provides users with more granular control, allowing them to decide how to handle specific issues rather than leaving it solely to the engine's automatic decisions.

To help us resolve your issue, we recommend reaching out to our support team via the “Report Issue” feature. Please explain your case in detail and attach the relevant log files so we can thoroughly analyze the problem. Sharing private information and logs on a public GitHub thread is challenging, so reaching out directly to support will allow us to address your issue more effectively. Once you have a ticket reference number, feel free to share it here, and we’ll help track the progress of your case.

Best regards.

**Comment by technikker** [comment] 2024-11-12 19:33
> As said above, I suggest report to them using the "report issue" button.

Did this before posting here.  They have not responded to my ticket as of yet.  Today I check and see the issue is magically resolved, I did not change anything.  Probably a server issue actually, even unrelated to my software update, but I'll be damned if I risk updating mega again for a while.


> Also when any weirdness occurs try logout and re-login it fixes 90% of issues for me

I'm well aware of all the little tricks you can try to get mega to behave. 

Tried this on all connected machines, also tried completely wiping mega, including appdata, downgrade back to 5.2, and the problem is still there (specifically I cannot download empty files (which are often created automatically as part of my projects), even from the web GUI, they will not download!!!)

Wasted hours on this before giving up and writing a python script to list all empty files, upload the list to mega, this file syncs correctly because it's not empty, then use another script on the remote side to ensure the file list exists with correct modification times, and mega stops forever looping trying to download the files.  If this is what I have to resort to, why don't I just write my own at this point?


TBH I think they fixed it because their servers were being bombarded with connections from all the files that were forever looping.

**Comment by vtmateos** [comment] 2024-11-15 11:13
Dear @technikker,

Our support team reached out for further details regarding the issue you experienced. Based on your message:

"Today I checked and noticed the issue has magically resolved. I did not change anything." 

it seems the problem is already solved.

We can confirm there was a temporary server issue related to 0-byte files, which was identified on November 11th and resolved within the same day. We sincerely apologize for any inconvenience this may have caused.

If you encounter any other specific issues, please don’t hesitate to let us know—we’ll be more than happy to assist. 
Thank you for your continued support!

Best regards.

**Comment by vtmateos** [comment] 2024-12-03 15:45
Hi @6d657263757279 ,
Apologies for the inconveniences.

The issue discussed in this thread was related to a problem with 0-byte files. Your report, however, appears to be about the completion of certain transfers. This could potentially be due to a temporary server-side issue. If you're still experiencing the problem and can reproduce it, please feel free to open a new issue.

For now, I will close this thread since the original reported issue has been confirmed as resolved and to keep issues organized.

Thank you for your understanding!

**Closed by vtmateos** 2024-12-03 15:45 UTC
