### ISSUE TITLE
not possible to set "No Proxy" back

### ISSUE THREAD

**Issue by garzaj** [meganz/MEGAsync#53] opened 2016-11-25 15:41 UTC
On the office I use a Proxy, but at home I don't. So after using it with a proxy I tried to change the settings to "no proxy". It is not possible, I always get : "Your proxy settings are invalid or your proxy doesn't respond":
![selection_018](https://cloud.githubusercontent.com/assets/1922533/20629847/e766735c-b32d-11e6-9ed4-1d62a9a41e54.png)

I'm using Linux Mint 18.

**Comment by polmr** [comment] 2016-11-28 11:12
@garzaj, a connectivity check is performed when you change the proxy settings. In case of failure, the changes won't be applied. I understand you've tried to change it to "No proxy" while at work (correct me if I'm wrong). You should change it at home. Also, ensure you have connectivity when you do it.

**Comment by garzaj** [comment] 2016-11-28 12:51
@polmr : I tried to change it several times while at home. At work I use the proxy. I only need the "No proxy" at home. Since I configured it once at work, i haven't been able to use Megasync at home. Very frustrating!

**Comment by polmr** [comment] 2016-11-28 16:30
Hi @garzaj,
I understand your frustation ...
The thing is ... even though megasync allowed you to change the proxy settings, it is likely to fail anyhow, since it wouldn't be able to connect. There are a couple of thigns you can do:
Could you please generate a log so that we can investigate a little further. In order to do so: please close MEGAsync, and run it in a terminal in this way:

megasync --debug > log.txt

Then try to reproduce the issue and close megasync.
Since the log could contain sensitive data (mainly file names) it would be better if you send it to support@mega.nz along with the the URL of this issue on GitHub. That way, the report should reach the developmenent team fast and we would carefully review it.

Also, 
the configuration, cache, etc. are stored at: "~/.local/share/data/Mega Limited/MEGAsync"
backup and remove that folder so as to have a clean instalation of megasync. Try to login then. This way we can determine if the connectivity check performed when disabling the settings is missbehaving.

**Comment by garzaj** [comment] 2016-11-28 16:36
The problem is that when trying to change to "No Proxy" it is trying to use the old proxa configuration and checking it, that shouldn't happen. I'll send you the log file.

**Comment by garzaj** [comment] 2016-11-28 16:43
Here the log.txt
[log.txt](https://github.com/meganz/MEGAsync/files/616894/log.txt)

**Comment by polmr** [comment] 2016-11-28 18:41
@garzaj looking at the log it seems that without proxy megasync is unable to connect. Exactly the same behaviour as if you'd disconnected the ethernet cable.
Please, ensure you can resolve g.api.mega.co.nz and also eu.static.mega.co.nz: What do you get with:

`nslookup g.api.mega.co.nz
`

and

`nslookup eu.static.mega.co.nz
`

Also, what do you get from the url (http://eu.static.mega.co.nz/?) (notice the ?)
`curl http://eu.static.mega.co.nz/? | grep title`

**Comment by garzaj** [comment] 2016-11-28 18:52
I just deleted all the config files. And it works. It is definitely a bug!

**Comment by polmr** [comment] 2016-11-29 16:08
@garzaj sorry to bother you, but could you give us the output of those commands, specially `curl http://eu.static.mega.co.nz/?` 

This way we can redesign the connectivity test which seems to be detecting a false negative in your case.

**Comment by garzaj** [comment] 2016-11-29 17:50
To repeat the exact conditions, I'll have to wait until Thursday, when I'm back home.

**Comment by joucoski** [comment] 2016-12-05 21:57
I'm having the same problem, the results are:

> Curl http://eu.static.mega.co.nz/? | grep title
   % Total% Received% Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
100 1894 100 1894 0 0 4102 0 -: -: - -: -: - -: -: - 4108
<Title> MEGA </ title>

> Nslookup g.api.mega.co.nz
Server: 127.0.1.1
Address: 127.0.1.1 # 53

Non-authoritative answer:
G.api.mega.co.nz canonical name = lu.api.mega.co.nz.
Name: lu.api.mega.co.nz
Address: 31.216.147.137
Name: lu.api.mega.co.nz
Address: 31.216.147.132
Name: lu.api.mega.co.nz
Address: 31.216.147.133
Name: lu.api.mega.co.nz
Address: 31.216.147.134
Name: lu.api.mega.co.nz
Address: 31.216.147.135nslookup g.api.mega.co.nz
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
g.api.mega.co.nz	canonical name = lu.api.mega.co.nz.
Name:	lu.api.mega.co.nz
Address: 31.216.147.137
Name:	lu.api.mega.co.nz
Address: 31.216.147.132
Name:	lu.api.mega.co.nz
Address: 31.216.147.133
Name:	lu.api.mega.co.nz
Address: 31.216.147.134
Name:	lu.api.mega.co.nz
Address: 31.216.147.135
Name:	lu.api.mega.co.nz
Address: 31.216.147.136

Name: lu.api.mega.co.nz
Address: 31.216.147.136

> nslookup eu.static.mega.co.nz
Server:		127.0.1.1
Address:	127.0.1.1#53

Non-authoritative answer:
Name:	eu.static.mega.co.nz
Address: 154.53.224.130
Name:	eu.static.mega.co.nz
Address: 154.53.224.134
Name:	eu.static.mega.co.nz
Address: 154.53.224.146

Please help me fix the problem!

**Comment by joucoski** [comment] 2016-12-05 22:01
Same problem, my log file 
[log.txt](https://github.com/meganz/MEGAsync/files/632398/log.txt)

Thanks by help!

**Comment by joucoski** [comment] 2016-12-05 22:05
I have the same problem.
[log.txt](https://github.com/meganz/MEGAsync/files/632415/log.txt)

Can help-me?

**Comment by polmr** [comment] 2016-12-07 09:36
It seems c-ares is having trouble resolving g.api.mega.co.nz. Even with fixed DNS servers.
Let's dig out: Could you please paste the outputs of these commands:
nslookup g.api.mega.co.nz 
nslookup g.api.mega.co.nz 154.53.224.130
nslookup eu.static.mega.co.nz 
nslookup eu.static.mega.co.nz 154.53.224.130
curl http://eu.static.mega.co.nz/?

Also, it'll be rather interesting if you give us some info about your system. OS, version, 64 vs 32 bits, ...
@joucoski, without configuration files/on a first run does it work for you too?
@garzaj, the output of curl command is quite unexpected, It does resolve eu.static.mega.co.nz but the contents are not those expected (hence, connectivity check fails and applying changes is not allowed). They should have included something like:
<title>MEGA</title>
It'll be really useful the entire output of the curl command.

Again, whatever you are not comfortable to write here, please write to support@mega.nz refering to this issue.

**Comment by joucoski** [comment] 2016-12-16 16:28
Hello, I would like to know if there is news about my problem? Thank you.

---
Emerson Joucoski


2016-12-09 15:26 GMT-02:00 Emerson Joucoski <joucoski@gmail.com>:

**Comment by garzaj** [comment] 2017-01-11 09:30
Is there any solution. I'm still having the same problem.

**Comment by polmr** [comment] 2017-01-11 12:55
@garzaj. Could you please give us the outputs of:
nslookup g.api.mega.co.nz
nslookup g.api.mega.co.nz 154.53.224.130
nslookup eu.static.mega.co.nz
nslookup eu.static.mega.co.nz 154.53.224.130
curl http://eu.static.mega.co.nz/?
@joucoski log indicates c-ares is failing due to ARES_ECONNREFUSED. We haven't been figured that out yet (apologies for the so late response, btw). In your case, it seems like the connectivity check we perform is failing. Those commands might help us see why.

**Closed** 2017-04-26 11:06 UTC

**Comment by muldon** [comment] 2019-10-08 12:31
same problem here... I can't connect anymore.. was using proxy before, now without proxy, the app does not start (loggin in...) forever... I tried to remove the config files, without success..

**Comment by rootsun** [comment] 2020-06-24 06:09
I love MEGA!
but this is kind of unreaonable since this issue was first post at 2016 and it still remains.

I mean can't I just disable mega proxy setting since my local proxy service is just not available?
It's not a problem, it's not a bug.
my LAN proxy server is just not working now and I can't find any replacement somehow for not short coming future.
So how am I gonna use my MEGA now?

**Comment by sarperen** [comment] 2021-02-01 14:59
I'm also having the same issue

**Comment by CK-Tex** [comment] 2022-02-24 03:46
btw, still facing the very same issue in 2022

**Comment by bytecode** [comment] 2022-11-27 01:55
we were planning to migrate from smartfile.net to mega.nz business , this issue is literally canceled the plan i was doing a presentation and it popped up while changing the proxy settings which made the client useless

**Comment by Songordon** [comment] 2024-05-19 11:03
vpn problem.

**Comment by ivsege** [comment] 2024-09-02 21:58
I'm having the same issue. Did anyone find a way to fix this?

**Comment by vtmateos** [comment] 2024-09-03 08:02
Hi,
Please could you confirm you are using latest client version from our website 5.4.1? Apart from that, please contact our support team to provide them log files so we can check what can be happening while setting the No proxy.
Apologies for the inconveniences.

**Comment by Ruhannn** [comment] 2024-11-27 04:00
please fix this

**Comment by JRSV** [comment] 2025-01-23 13:41
today I woke up to this bug. Settings in Mega open directly in proxy settings and if I pick no proxy the "your proxy settings are invalid ..." appears. I have deleted the configuration folder and no change. Log In does not happen.

**Comment by iagogv3** [comment] 2025-03-20 09:46
Currently MEGA keeps hangged trying logging in and if I try No proxy I get this issue
