### ISSUE TITLE
Folder Icon override on MEGAsync restart (windows)

### ISSUE THREAD

**Issue by hogoll** [meganz/MEGAsync#791] opened 2023-03-14 22:09 UTC
When I synced folders to MEGA, program changed the custom icons of my folders to its own.

![Screenshot_950](https://user-images.githubusercontent.com/127900079/225151272-8041f832-058e-449d-a6bb-cae690d7d268.jpg)

All I had to do then was change the folder icons back to my own again, and the custom icons will remain. But now when I restart MEGAsync (or restart PC), the program starts replacing folder icons with its own again (even if the folder has a default icon), and I have to change the folder icons again until the next reboot, and I have to do it again.

I installed MEGAsync on fresh VM with windows and and it acts the same, so problem is not on my side

**Comment by thebodzio** [comment] 2023-03-17 11:08
As a side-note: very similar thing happens with Windows Explorer left panel icons. Even if I explicitly remove them (I don't need them), they are back again, come reboot or app restart. I can open separate bug report, but somehow I think these two things are, at least somewhat, related.

Also, if I remove icons from left panel, I can't find a way to restore them (either selectively or in total), if, for any reason, I will need them.

**Comment by castigo86** [comment] 2023-03-20 07:20
This issue has affected me since 4.8.7. I think is related to [this open issue](https://github.com/meganz/MEGAsync/issues/777).

**Comment by thebodzio** [comment] 2023-03-20 10:20
@castigo86 Great find! Thank you! 👍 Let me add my 2¢ to that one.

**Comment by Perkolator** [comment] 2023-03-31 13:26
I contacted mega support about this and 4 weeks ago I received this message from them:

> We have confirmed with our developers that the current icon is updated on every startup hence the customised icon can not be kept at the moment.
Our developers are currently working on a rework release and future releases will allow you to keep the customised icon unchanged.
Unfortunately, we do not have an estimated time for the release at the moment, please keep your Desktop app with the most updated version.

**Comment by hyperjit** [comment] 2023-05-21 22:04
Guess this has been fixed in the latest update (at least on my Windows 10 22H2, MEGASync v4.9.4). I don't see the folder icons resetting to the custom MEGA folder icon now.

**Comment by thebodzio** [comment] 2023-05-22 10:02
Seems legit. I can confirm that changing the icons and re-adding shortcuts to Explorer's side panel is fixed in Windows 10 22H2.

The other thing is how to re-add panel shortcuts, but that's a different story 😊

**Comment by Perkolator** [comment] 2023-05-22 10:18
Seems to be fixed in Linux too (v4.9.4).

Why was this not informed to users by mega? Not a single mention in this issue (and not closing it). And of course, no mention in the changelog either (which they ignore to make more informative/correct although many times asked, the changelog is totally unusable/uninformative). The way mega staff runs this repo is inadequate and not very user friendly.

**Comment by castigo86** [comment] 2023-05-22 11:34
Just commenting to confirm that this issue seems solved on windows with 4.9.4.

**Closed** 2023-05-22 11:41 UTC
