### ISSUE TITLE
hangs on logging in

### ISSUE THREAD

**Issue by raggoo** [meganz/MEGAsync#34] opened 2016-09-10 07:52 UTC
It hangs for days on "logging in".

I cannot get  to the account to change anything as when I go to settings all it will let me do is change the proxy which I have changed to no proxy and auto detect and makes no difference.

Win7.

I have tried everything I can think of.

It is "hung" more than I get to use it.

Reinstalled, no firewall, no virus control.

It finally resolves itself after a few days but is most frustrating.

What causes it?

How to FIX it?

How to AVOID it?

Thanks.

**Comment by Logic-gate** [comment] 2016-09-12 21:19
I had a similar issue on Sept, 4. It was caused by a server overload. https://twitter.com/MEGAprivacy/status/772535642068615169

**Comment by raggoo** [comment] 2016-09-12 21:34
I just found out what my problem was - there have my IP  address blocked or something!

I cannot use it at all with normal IP . (US)

If I use proxy across the world somewhere works fine!

Weird.

**Comment by AleksandarSavic95** [comment] 2017-11-14 14:50
This happened to me after using wifi with a proxy. When I came back home, where there is no proxy, it just wouldn't sync. It was stuck on "logging in" message forever. The only thing I could do is:

- Right-click on megaSync icon in the taskbar
- Select _Settings_ (being the only option besides _Exit_)
- in the only available tab, Proxy settings tab, change from _Auto-detect_ to **_No proxy_**
- Now the client should start syncing (the first message I got was "Fetching files list", or something like that)

Good luck with fixing this! 👍

**Comment by lilajui** [comment] 2019-05-17 13:10
Hi, I am also not able to log in for more than a week and I tried to do the same as you, but got no results. Any other ideas?

**Comment by polmr** [comment] 2019-05-22 17:47
Hi,

Apologies for the inconveniences. The problem could be a temporary server side issue. If the problem persists, please contact support for a deep analysis via support@mega.nz. They will guide you to provide required information and log file to be analysed and find out the cause of your issue.

Kind regards.

**Comment by muldon** [comment] 2019-10-07 19:15
same issue here about logging in...

**Comment by lilajui** [comment] 2019-10-08 11:14
> same issue here about logging in... using the ubuntu version.

In my case, after searching a lot, I found out that this was happening due to a change in the configurations of the firewall. Hope this will help

**Comment by muldon** [comment] 2019-10-08 12:13
This issue stopped my works... I'd better go back to dropbox...

**Comment by mkuhring** [comment] 2019-10-23 19:00
I'm having the same issue for two weeks now on a Windows 10 computer, while it is working properly on two other Windows 10 computers I sync with the same account. Since this one is a work computer, I'm currently in contact with our IT department whether they changed something in the firewall. Or maybe our institute's IPs got blocked completely for some reason, who knows. I haven't tried connecting via a proxy yet, that might be a temporay workaround. I'll keep you updated.

Beside that issue, I really prefer Mega over all the other services. So keep up the good work!

**Comment by ElPrinz** [comment] 2020-08-03 06:26
It works for me! 
Follow this video:
https://www.youtube.com/watch?v=fYyEedhqpHU

**Comment by Mountain-Eagle** [comment] 2023-11-19 20:11
Windows 10 Pro, Firefox 119.0.1 (using Cloudflare secure DNS), Mega 64 bit 4.10.0, Proton free VPN WireGuard on US server, HP ProBook 650 G8, Wi-Fi 5 ac, DNS 9.9.9.9, 1.0.0.2
It was hung at logging in while using Proton free VPN on a US server.
It worked when I switched to a different Proton free VPN US server.
Unknown cause, could be blocked VPN IP address, overloaded VPN, bad connection, busy server, etc.
I have occasionally seen other unusual, non-responsive, and blocked connection behavior on other websites that was solved by switching to another Proton free VPN US server.

**Comment by sillynimbus** [comment] 2023-11-21 12:32
Having this issue. Clearing cache/cookies or opening in incognito was working for a bit but it's back to being unresponsive. I also can't load any mega.nz link or login on the website. Tried different browsers/restarting computer/internet and no dice. Not sure why this is happening

**Comment by imagochan** [comment] 2023-11-28 19:54
> happening for me in Nov 2023.

it works for me now (I had this issue yesterday), seems to be a server-side issue maybe?

**Comment by ivsege** [comment] 2024-09-02 21:39
I'm having the same issue. I've tried many things, but I can't log in on my Wi-Fi. It works fine on my phone when not connected to my Wi-Fi though.

**Comment by vtmateos** [comment] 2024-12-03 15:52
Dear users,
Apologies for the inconveniences.

Many of these issues could be related with a temp server issue or a problem with local network (dns not resolving, antivirus or firewall...)

In case you experience this issue, please create a ticket to analyse individually. Meanwhile, I will proceed to close this ticket.

Thanks.

**Closed by vtmateos** 2024-12-03 15:52 UTC
